[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Remappings (MOVED OUT of etherscan section)
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@pythnetwork/=lib/pyth-sdk-solidity/",
    "forge-std/=lib/forge-std/src/"
]

# RPC Endpoints
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

# Etherscan API Configuration
[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
